NOTA1 = float (input("ingrese nota 1: "))
NOTA2 = float (input("ingrese nota 2: "))
NOTA3 = float (input("ingrese nota 3: "))
NOTA4 = float (input("ingrese nota 4: "))
NOTA5 = float (input("ingrese nota 5: "))
NOTA6 = float (input("ingrese nota 6: "))
NOTA7 = float (input("ingrese nota 7: "))
NOTA8 = float (input("ingrese nota 8: "))
NOTA9 = float (input("ingrese nota 9: "))
NOTA10 = float (input("ingrese nota 10: "))
PROMEDIO = (NOTA1+NOTA2+NOTA3+NOTA4+NOTA5+NOTA6+NOTA7+NOTA8+NOTA9+NOTA10)/10
print ("El promedio es: ", PROMEDIO)

